export enum ActionTexts {
  TITLE = "Wie kann ich mich verhalten?",
  COUNTY_TEASER_1 = "Informiere Dich über aktuelle Verhaltensregeln für ",
  COUNTY_TEASER_2 = " hier.",
  INTRO_TEASER_1 = "Die Pandemie ist noch nicht vorbei und wir alle haben das Ziel die Pandemie soweit es geht einzudämmen und natürlich Risikogruppen zu schützen. Besonders die bevorstehende kalte Jahreszeit, in der wir uns überwiegend in geschlossen Räumen aufhalten, stellt eine Herausforderung dar. Es kommt jetzt auf Dich, auf uns, auf jeden Einzelnen an!",
  INTRO_TEASER_2 = "In den letzten Monaten konnte immer wieder gezeigt werden, dass ganz einfache Maßnahmen, die von jedem umgesetzt werden können, sehr viel Wirkung haben. ",
  CONTACT_HEADLINE = "Kontakte reduzieren",
  CONTACT_TEXT = "Kontakte reduzieren ist eine der wirkungsvollsten Maßnahmen.\n Das Virus wird von Mensch-zu-Mensch übertragen. Wenn man sich nicht trifft, kann das Virus also nicht übertragen werden. Greife zum Telefonhörer, halte eine Videokonferenz und arbeite von zu Hause, wann immer dies möglich ist. So schwer es auch fällt, Kontakte minimieren schützt und hilft uns allen, vor allem in Risikogebieten. Seid dabei und helft mit!",
  DISTANCE_HEADLINE = "Abstand halten",
  DISTANCE_TEXT = "Falls Du Kontakt zu einer Person hast, dann halte einen Abstand von mindestens 1.5 Metern. Je mehr Abstand, umso besser.",
  MASK_HEADLINE = "Maske tragen",
  MASK_TEXT = "Wenn Du infiziert bist und Du eine Alltagsmaske trägst, verringert sich das Risiko, dass Du andere Personen ansteckst. Sind Kontakte nicht vermeidbar, kann das Tragen einer Maske also sowohl Dich, als auch Dein Gegenüber schützen.",
  VENTILATION_HEADLINE = "Regelmäßig lüften",
  VENTILATION_TEXT = "Das Virus kann über die Luft übertragen werden.\nWenn Du Dich mit anderen Personen triffst, dann tue dies am besten an der frischen Luft.\nFalls Du Dich doch in einen geschlossenen Raum begeben musst, dann sorge für eine gute Luftzirkulation, indem Du Fenster öffnest und gut lüftest.",
  HYGIENE_HEADLINE = "Hygienemaßnahmen",
  HYGIENE_TEXT = "Hygienemaßnahmen können Infektionen verringern.\nDas Verwenden von Desinfektionsmitteln und das Händewaschen können dazu beitragen, Infektionen zu verhindern, wenn Du Dinge angefasst hast, die potentiell mit dem Virus kontaminiert sind.",
  REGIONAL_HEADLINE = "Lokale Regeln",
  REGIONAL_TEXT = "Informiere Dich über lokale Regeln und Maßnahmen in Deiner Region.",
  FINAL_TEASER = "Zusammen können wir es schaffen!\nGegenseitige Rücksichtnahme, Verständnis und Geduld sind die Gebote dieser Stunde.",
}
