image: gitpod/workspace-full

tasks:
  - init: yarn install && yarn run build
    command: yarn run dev

vscode:
  extensions:
    - esbenp.prettier-vscode@5.7.1:GDba64T6G+TUi1qmc6BE3A==

ports:
  - port: 8080
    onOpen: open-browser
