---
enabled: true
restylers:
  - prettier:
      image: restyled/restyler-prettier:v2.0.2-1
      include:
        - "**/*.js"
        - "**/*.ts"
        - "**/*.jsx"
        - "**/*.tsx"
        - "**/*.html"
        - "**/*.md"
        - "**/*.yml"
        - "**/*.yaml"
        - "**/*.json"
        - "**/*.css"
        - "**/*.scss"
