version: "3.0"
services:
  nginx:
    # https://hub.docker.com/_/nginx
    image: nginx:1.19-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./data/html:/usr/share/nginx/html
      - ./data/nginx:/etc/nginx
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    # https://hub.docker.com/r/certbot/certbot/
    image: certbot/certbot
    container_name: certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  openmaptiles:
    image: klokantech/openmaptiles-server
    volumes:
      - ./data/openmaptiles:/data
    restart: always
