name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEPLOYMENTACCESSKEY }}
        aws-secret-access-key: ${{ secrets.DEPLOYMENTACCESSSECRET }}
        aws-region: eu-central-1
    - name: Build static site
      run: npm install && npm run-script build
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./dist/ s3://covmapper-webinterface --delete
