on:
  pull_request_target:
jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      ref: ${{github.event.pull_request.head.ref}}
      repository: ${{github.event.pull_request.head.repo.full_name}}
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build:prod
    - name: Upload bundle-stats.json
      uses: actions/upload-artifact@v1
      with:
        name: head-stats
        path: ./bundle-stats.json
  build-base:
    name: 'Build base'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      ref: ${{github.event.pull_request.base.ref}}
      repository: ${{github.event.pull_request.base.repo.full_name}}
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn build:prod
    - name: Upload bundle-stats.json
      uses: actions/upload-artifact@v1
      with:
        name: base-stats
        path: ./bundle-stats.json
  compare:
    name: 'Compare base & head bundle sizes'
    runs-on: ubuntu-latest
    needs: [build-base, build-head]
    steps:
    - uses: actions/checkout@v1
    - name: Download base artifact
      uses: actions/download-artifact@v1
      with:
        name: base-stats
    - name: Download head artifact
      uses: actions/download-artifact@v1
      with:
        name: head-stats
    - name: Diff between base & head
      uses: weltenwort/webpack-stats-diff-action@v1.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base_stats_path: ./base-stats/bundle-stats.json
        head_stats_path: ./head-stats/bundle-stats.json
