name: Crowdin

on:
  push:
    branches: [ master ]
  schedule:
   - cron: '0 3 * * *'

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@1.0.13
      with:
        # upload sources option
        upload_sources: true

        # upload translations options
        #upload_translations: true
        #upload_language: 'de'
        #auto_approve_imported: true
        #import_eq_suggestions: true

        # download translations options
        download_translations: true
        #skip_untranslated_strings: true
        skip_untranslated_files: true
        export_only_approved: true
        push_translations: true
        commit_message: 'fix(translation): update translations'

        # This is the name of the git branch that Crowdin will create when opening a pull request.
        # This branch does NOT need to be manually created. It will be created automatically by the action.
        #localization_branch_name: l10n_crowdin_action
        create_pull_request: true
        pull_request_title: 'fix(translation): update translations from crowdin'
        pull_request_body: 'There are new Crowdin translations. Merging this PR will update them.'
        pull_request_labels: 'enhancement'
        # This is the name of the git branch to with pull request will be created.
        # If not specified default repository branch will be used.
        #pull_request_base_branch_name: not_default_branch

        # global options

        config: './crowdin.yml'

        # A personal access token, not to be confused with Crowdin API v1 "API key"
        # See https://crowdin.com/settings#api-key to generate a token
        token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
        project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
