name: PR-Checks
on:
  pull_request_target:
#    branches: [ master ]
    paths-ignore:
#      - '.github/**'
      - '.hosting/**'

env:
  RESSOURCE_GROUP: covmapper
  STORAGE_NAME: covmapperpr${{ github.event.pull_request.number }}

jobs:
  build-head:
    name: 'Build head'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: '${{github.event.pull_request.head.ref}}'
        repository: '${{github.event.pull_request.head.repo.full_name}}'
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - uses: actions/cache@v2
      id: yarn-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Install dependencies
      if: steps.yarn-cache.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      run: yarn build
    - name: Upload bundle-stats.json
      uses: actions/upload-artifact@v1
      with:
        name: head-stats
        path: ./bundle-stats.json
    - name: Upload dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ./dist


  e2e-test:
    name: "E2E Tests"
    runs-on: ubuntu-latest
    needs: [build-head]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: '${{github.event.pull_request.head.ref}}'
        repository: '${{github.event.pull_request.head.repo.full_name}}'
    - name: remove unneeded files
      run: rm package.json
    - name: Download base artifact
      uses: actions/download-artifact@v1
      with:
        name: dist
    - name: Install TestCafe BrowserStack plugin
      run: npm install testcafe-browser-provider-browserstack
    - name: install testcafe
      run: yarn add http-server testcafe testcafe-browser-provider-browserstack
    - name: 'BrowserStack Env Setup'
      uses: 'browserstack/github-actions/setup-env@master'
      with:
        username:  ${{ secrets.BROWSERSTACK_USERNAME }}
        access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        build-name: 'covmapperpr${{ github.event.pull_request.number }}'
        project-name: 'CovMap'
    - name: test
      run: yarn run testcafe 'browserstack:chrome:Windows 10' testcafe/*.spec.ts --app "cd ./dist && http-server -p 8080"

#    - name: Find Comment
#      uses: peter-evans/find-comment@v1
#      id: fc
#      with:
#        issue-number: ${{ github.event.pull_request.number }}
#        body-includes: This PR is available as a preview
#
#    - name: Create comment
#      if: ${{ steps.fc.outputs.comment-id == 0 }}
#      uses: peter-evans/create-or-update-comment@v1
#      with:
#        issue-number: ${{ github.event.pull_request.number }}
#        body: |
#          This PR is available as a preview [here](https://${{ env.STORAGE_NAME }}.z16.web.core.windows.net).
#        reaction-type: "rocket"
