name: PR - Preview
on:
  pull_request:
    branches: [ master ]
    
env:
  RESSOURCE_GROUP: covmapper
  STORAGE_NAME: covmapperpr${{ github.event.pull_request.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install Packages
      run: npm install
    - name: Build
      run: npm run-script build -- --env prod
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: web-app
        # Directory containing files to upload
        path: ./dist/

    # Setup Preview
    - name: Azure Login
      uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az storage account create --kind StorageV2 --name ${{ env.STORAGE_NAME }} --resource-group ${{ env.RESSOURCE_GROUP }} --subscription ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
          az storage blob service-properties update --account-name ${{ env.STORAGE_NAME }} --static-website --404-document 404.html --index-document index.html --subscription ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
          export key=$(az storage account keys list --account-name ${{ env.STORAGE_NAME }} --resource-group  ${{ env.RESSOURCE_GROUP }} --subscription ${{ SECRETS.AZURE_SUBSCRIPTION_ID }} --query "[0].value")
          az storage blob upload-batch -d '$web' -s ./dist/ --account-name ${{ env.STORAGE_NAME }} --account-key $key --subscription ${{ SECRETS.AZURE_SUBSCRIPTION_ID }}
    - name: Create comment
      uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          This PR is available as a preview [here][1].
          [1]: https://${{ env.STORAGE_NAME }}.z16.web.core.windows.net/
        reaction-type: "rocket"
