name: Release
on:
  push:
    branches:
      - master
jobs:
  test:
    name: Test
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Build
        run: yarn build
      - name: test
        run: yarn run test-ci

  release:
    name: Release
    runs-on: ubuntu-18.04
    needs: [test]
    outputs:
      released: ${{ steps.semantic.outputs.RELEASED }}
      version: ${{ steps.semantic.outputs.VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install
      - name: Release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn run semantic-release
      - name: Upload dist
        if: steps.semantic.outputs.released == 'true'
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: [release]
    if: ${{ needs.release.outputs.released == 'true' }}
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOYMENTACCESSKEY }}
          aws-secret-access-key: ${{ secrets.DEPLOYMENTACCESSSECRET }}
          aws-region: eu-central-1
      - name: Download dist artifact
        uses: actions/download-artifact@v1
        with:
          name: dist
      - name: Deploy static site to covmapper.com
        run: aws s3 sync ./dist/ s3://covmapper-webinterface --delete
      - name: Deploy static site to covmap.de
        run: aws s3 sync ./dist/ s3://covmap-production --delete
